import { readdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../dist/', import.meta.url));
async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const lists = await Promise.all(entries.filter(entry => !entry.name.startsWith('.')).map(entry => entry.isDirectory() ? walk(path.join(directory, entry.name)) : [path.join(directory, entry.name)]));
  return lists.flat();
}
const files = (await walk(root)).filter(file => path.basename(file) !== 'precache.js').sort();
const hash = createHash('sha256');
for (const file of files) { hash.update(path.relative(root, file)); hash.update(await readFile(file)); }
const assets = ['./', ...files.filter(file => !file.endsWith('/sw.js')).map(file => './' + path.relative(root, file).split(path.sep).join('/'))];
await writeFile(path.join(root, 'precache.js'), '// Generated by npm run build. Do not edit.\nself.PLAYROOM_VERSION = ' + JSON.stringify(hash.digest('hex').slice(0, 14)) + ';\nself.PLAYROOM_ASSETS = ' + JSON.stringify(assets, null, 2) + ';\n');
console.log(`Static platform ready: ${assets.length} offline assets. Deploy the dist directory.`);
